import React from "react";
import Accordion from "react-bootstrap/Accordion"
import "../style/FAQs.css";

export default function FAQsPage() {
    return (
        <div className="FAQPage">

            <div className="QA">
                <Accordion defaultActiveKey="0">
                    <Accordion.Item eventKey="0">
                        <Accordion.Header> Do I need an account to use the website?</Accordion.Header>
                        <Accordion.Body>
                            <strong>You don't need an account to use the basic functions of the website.</strong> <br/>
                            But you need one if you want to create and manage your own recipes, save your favourites or use the adventurize function.
                        </Accordion.Body>
                    </Accordion.Item>
                    <Accordion.Item eventKey="1">
                        <Accordion.Header>Do I have to pay for an account?</Accordion.Header>
                        <Accordion.Body>
                            <strong>No, you don't have to pay for an account. </strong> <br/>
                            It's completely free.
                        </Accordion.Body>
                    </Accordion.Item>
                    <Accordion.Item eventKey="2">
                        <Accordion.Header>Can I save my favorite recipes for easy access?</Accordion.Header>
                        <Accordion.Body>
                            <strong>Yes you can</strong>,  <br/> the website allows you to like your favorite recipes and look them up in your profile or on the My Recipes page.
                        </Accordion.Body>
                    </Accordion.Item>
                    <Accordion.Item eventKey="3">
                        <Accordion.Header>Can I adjust a recipe to fit the number of servings I need?</Accordion.Header>
                        <Accordion.Body>
                            <strong>Yes</strong>,  <br/> you can specify the number of servings you need directly on the recipe page and it will automatically be adjusted.
                        </Accordion.Body>
                    </Accordion.Item>
                    <Accordion.Item eventKey="4">
                        <Accordion.Header>What exactly means adventurize a recipe?</Accordion.Header>
                        <Accordion.Body>
                            <strong>It's like a short story guiding you through the recipe!</strong>  <br/> It is an AI-generated story, adjusted to your recipe, making the cooking experience more exciting and thrilling.
                        </Accordion.Body>
                    </Accordion.Item>
                    <Accordion.Item eventKey="5">
                        <Accordion.Header>How can I adventurize a recipe?</Accordion.Header>
                        <Accordion.Body>
                            <strong>You need an account to be able to adventurize a recipe!</strong>  <br/> When you are logged in, you can scroll down when on a recipe page and press the adventurized button. A story will be generated with AI and you can decide to save it or generate a new one.
                        </Accordion.Body>
                    </Accordion.Item>
                    <Accordion.Item eventKey="5">
                        <Accordion.Body className="disclaimer">
                            <strong>!Disclaimer!</strong>  <br/>  The short stories are generated by artificial intelligence and may contain errors, inaccuracies, or omissions. Please cross-check with reliable sources or the original recipe to ensure correct recipe details and follow safety guidelines. The content may also include unintended sensitive material; reader discretion is advised.
                        </Accordion.Body>
                    </Accordion.Item>
                </Accordion>
            </div>
        </div>
    );

}
