import "bootstrap/dist/css/bootstrap.min.css";
import "../style/FoodForge.css";
import * as React from "react";
import CookPot from "../assets/newRecipe/Cook_Pot.png";
import CookPotCover from "../assets/newRecipe/Cook_Pot_Cover.png";
import AddIngredientApp from "../components/AddIngredientApp";
import DifficultyRadioGroup from "../components/DifficultyRadioGroup";
import FormPropsTextFields from "../components/FormPropsTextFields";
import ImageUploader from "../components/ImageUploader";
import Carlos_PopUp from "../helpers/Carlos_PopUp";


export default function FoodForge() {


    return (

        <div id={"Main-Container"}>


            <div id={"Left-Container"}>

                <div id={"Left-Inner-Container"}>

                    <img src={CookPotCover} alt="potTop" style={{position: 'relative', width: '80%'}}/>
                    <AddIngredientApp/>
                    <img src={CookPot} alt="potBottom" style={{position: 'relative', width: '80%'}}/>

                </div>

            </div>


            <div id={"Right-Container"}>

                <br/>
                <h1 className={"header"}>FOOD FORGE</h1>
                <br/>

                <div className={"Top-Right-Container"}>

                    <div id={"LeftSide"}>
                        <ImageUploader/>
                    </div>

                    <div id={"RightSide"}>
                        <div className={"choose"}>
                            <strong>Choose the difficulty of the recipe</strong>
                        </div>

                        <div className={"group"}>
                            <DifficultyRadioGroup/>
                        </div>
                    </div>

                </div>


                <div id={"Bottom-Right-Container"}>

                    <br/><br/><FormPropsTextFields/><br/>

                    <textarea className="textArea"></textarea>
                    <br/>

                    <span className={"buttons"}>
                        <br/>
                        <a className="Save-Recipe-Button" href='/myRecipes'>
                            <button className="save-recipe">SAVE RECIPE</button>
                        </a>
                        <div className="carlos">
                            {Carlos_PopUp(
                                "Need help?",
                                "Len, you are the best Time-Tracker Manager " +
                                "we could ever ask for. You are always on time and you always " +
                                "keep us on track. You are the best! - auto generated by Carlos-AI"
                            )}
                        </div>
                    </span>

                </div>
            </div>

        </div>
    );
}

