import * as React from 'react';
import "../style/Impressum.css"

export default function Impressum() {

    return (

        <div className="ImpressumPage">

            <div className="header">
                <h1>Impressum</h1>
            </div>


            <div className="body">

                <div className="content">
                    <br/><br/>
                    <h2>Angaben gemäß § 5 TMG:</h2>
                    <br/>
                    <p>
                        Mr. Anderson<br/>
                        Musterstraße 123<br/>
                        76222 Karlsruhe</p>
                    <br/><br/>

                    <h2>Kontakt:</h2>
                    <br/>
                    <p>Telefon: 01234 56789<br/>
                        E-Mail: <a href="mailto:mr.anderson@softwareengineering.com">mr.anderson@softwareengineering</a>
                    </p>
                    <br/>

                    <h2>Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:</h2>
                    <p>
                        Marc Siegfarth<br/>
                        Nick Hörner<br/>
                        Stefan Mergl<br/>
                        Len Vesjada
                    </p>
                    <br/><br/>

                    <h2>Haftungsausschluss (Disclaimer):</h2>
                    <br/><br/>

                    <h3>Haftung für Inhalte</h3>
                    <br/>
                    <p>Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den
                        allgemeinen Gesetzen verantwortlich. ...</p>
                    <br/><br/>

                    <h3>Haftung für Links</h3>
                    <br/>
                    <p>Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss
                        haben. ...</p>
                    <br/><br/>

                    <h3>Urheberrecht</h3>
                    <br/>
                    <p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem
                        deutschen Urheberrecht. ...</p>
                    <br/><br/>
                    <h3>AI Generation</h3>
                    <br/>
                    <div className="disclaimer-text">
                        <p><strong>!Disclaimer!</strong><br/><br/>

                            The short stories were generated by artificial intelligence. While it aims to guide you
                            through the recipe in an engaging manner, please be aware of the following:<br/><br/>

                            <strong>Potential Errors and Inaccuracies:</strong><br/> The AI-generated content may
                            contain errors,
                            inaccuracies, or omissions. Always cross-check with a reliable source or the original recipe
                            to ensure correct measurements, techniques, and ingredients.<br/><br/>

                            <strong>Safety and Allergens:</strong><br/> Ensure that all cooking and safety practices are
                            followed. The AI may
                            not account for individual dietary restrictions, allergies, or specific cooking safety
                            guidelines.<br/><br/>

                            <strong> Content Sensitivity:</strong><br/> The story is generated without human oversight
                            and may inadvertently
                            include content that some readers find offensive or inappropriate. Reader discretion is
                            advised.<br/><br/>

                            By using this AI-generated content, you acknowledge these potential issues and agree to use
                            it at your own risk. The creator of this content assumes no responsibility for any
                            inaccuracies or adverse outcomes resulting from its use.
                        </p>
                    </div>
                    <br/><br/>
                </div>

            </div>


        </div>
    );
}
